FROM jenkins/jenkins:lts

USER root

# Install Docker CLI + Compose
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    usermod -aG docker jenkins

# Switch back to Jenkins user
USER jenkins
