FROM jenkins/jenkins:lts

USER root

# Install docker + docker-compose
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    groupadd -f docker && \
    usermod -aG docker jenkins

USER jenkins
